version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU11-ubuntu-22.04
    environment:
      ACCEPT_EULA: "Y"  # Required for SQL Server licensing
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}  # Environment variable for SA account password
    ports:
      - "1433:1433"
    container_name: people4business-blog-db
    volumes:
      - ./sql_data:/var/opt/mssql/data